version: '1.0'

#version: "3.9"
services:
  influx:
    image: influxdb:1.8
    #container_name: grafana
    restart: unless-stopped
    ports:
      - '8086:8086'
    environment:
      INFLUXDB_DB: heat
    expose:
      - 8086
