#/root/mqtt_home/infra/haproxy
services:
  haproxy:
    image: haproxytech/haproxy-alpine:3.1

    ports:
      - '8085:8085'
      - '8085:8085'
      - '8404:8404'
    volumes:

      - '/root/mqtt_home/infra/haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg'
      - '/root/mqtt_home/infra/haproxy/magictokens.lua:/usr/local/etc/haproxy/magictokens.lua'
      - '/root/mqtt_home/infra/haproxy/decode.lua:/usr/local/etc/haproxy/decode.lua'
      - '/root/mqtt_home/infra/haproxy/encode.lua:/usr/local/etc/haproxy/encode.lua'      
      - '/root/mqtt_home/infra/haproxy/print_berrer.lua:/usr/local/etc/haproxy/print_berrer.lua'
      - '/root/letsencrypt/etc-letsencrypt/archive:/usr/local/etc/haproxy/archive'

      #- '/home/wojciech/idk2.pem:/usr/local/etc/haproxy/dev34.pem'      
      #- '/app/smartkyc/servers/ssl.test:/usr/local/etc/ssl/cong'
    restart: unless-stopped
    expose:
      - "8085"
      - "8404"
      - "8084"
 #   networks:
 #     - skyc
  #    - haproxy
#volumes:
#  logs:
#  stashdata:
#networks:
#  skyc:
#  haproxy:
#    external: true  
