#/root/mqtt_home/infra/haproxy
services:
  haproxy:
    image: haproxytech/haproxy-alpine:3.1

    ports:
      - '8085:8085'
      - '8085:8085'
      - '8404:8404'
    volumes:

      - '/root/mqtt_home/infra/haproxy/haproxy.file:/usr/local/etc/haproxy/haproxy.cfg'
      - '/root/mqtt_home/infra/haproxy/jwtverify.lua:/usr/local/etc/haproxy/jwtverify.lua'
      - '/root/mqtt_home/infra/haproxy/magictokens.lua:/usr/local/etc/haproxy/magictokens.lua'
      - '/root/mqtt_home/infra/haproxy/json.lua:/usr/local/etc/haproxy/json.lua'
      - '/root/mqtt_home/infra/haproxy/base64.lua:/usr/local/etc/haproxy/base64.lua'
      - '/root/mqtt_home/infra/haproxy/crypto.lua:/usr/local/etc/haproxy/crypto.lua'
      - '/root/mqtt_home/infra/haproxy/print_berrer.lua:/usr/local/etc/haproxy/print_berrer.lua'
      #- '/home/wojciech/idk2.pem:/usr/local/etc/haproxy/dev34.pem'      
      #- '/app/smartkyc/servers/ssl.test:/usr/local/etc/ssl/cong'
    restart: unless-stopped
    expose:
      - "8085"
      - "8404"
      - "8084"
 #   networks:
 #     - skyc
  #    - haproxy
#volumes:
#  logs:
#  stashdata:
#networks:
#  skyc:
#  haproxy:
#    external: true  
